#! /usr/bin/perl

use strict;
use Cwd;
use File::Basename;
use File::Spec;

sub magic_number_matches {
  return 0 unless -e '_build/magicnum';
  local *FH;
  open FH, '_build/magicnum' or return 0;
  my $filenum = <FH>;
  close FH;
  return $filenum == 855416;
}

my $progname;
my $orig_dir;
BEGIN {
  $^W = 1;  # Use warnings
  $progname = basename($0);
  $orig_dir = Cwd::cwd();
  my $base_dir = '/Users/cholt/Developer/cnv_caller-0.001/src';
  if (!magic_number_matches()) {
    unless (chdir($base_dir)) {
      die ("Couldn't chdir($base_dir), aborting\n");
    }
    unless (magic_number_matches()) {
      die ("Configuration seems to be out of date, please re-run 'perl Build.PL' again.\n");
    }
  }
  unshift @INC,
    (
     '/Users/cholt/Developer/cnv_caller-0.001/src/../lib',
     '/Users/cholt/Developer/cnv_caller-0.001/src/../perl/lib',
     '/Users/cholt/Developer/cnv_caller-0.001/src/lib',
     '/Users/cholt/Developer/cnv_caller-0.001/src/inc/perl/lib',
     '/Users/cholt/Developer/cnv_caller-0.001/src/inc/lib',
     '/sw/lib/perl5/5.12.3/darwin-thread-multi-2level',
     '/sw/lib/perl5/5.12.3',
     '/sw/lib/perl5/darwin-thread-multi-2level',
     '/sw/lib/perl5',
     '/sw/lib/perl5/darwin',
     '/usr/local/cegma/lib',
     '/usr/local/eval',
     '/usr/local/my_perl_lib',
     '/usr/local/bioperl-run',
     '/usr/local/bioperl-live',
     '/usr/local/perl/lib'
    );
}

close(*DATA) unless eof(*DATA); # ensure no open handles to this script

use INSTALL::Build;
Module::Build->VERSION(q{0});

# Some platforms have problems setting $^X in shebang contexts, fix it up here
$^X = Module::Build->find_perl_interpreter;

if (-e 'Build.PL' and not INSTALL::Build->up_to_date('Build.PL', $progname)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.\n";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = INSTALL::Build->resume (
  properties => {
    config_dir => '_build',
    orig_dir => $orig_dir,
  },
);

$build->dispatch;
